//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace FelineSoft.CatFlap.NorthwindTests
{
    public class EmployeeUpdateTest
    {
        [MapTo(typeof(DomainModel.Employee), "EmployeeID")]
        public System.Int32 ID { get; set; }

        public System.String LastName { get; set; }

        public System.String FirstName { get; set; }

        public System.String Title { get; set; }

        public System.Nullable<System.DateTime> BirthDate { get; set; }

        public System.String Notes { get; set; }

        public System.Collections.Generic.ICollection<TerritoryUpdateTest> Territories { get; set; }
    }

    public class RegionUpdateTest
    {
        [MapTo(typeof(DomainModel.Region), "RegionID")]
        public System.Int32 ID { get; set; }

        public System.String RegionDescription { get; set; }
    }

    public class TerritoryUpdateTest
    {
        [MapTo(typeof(DomainModel.Territory), "TerritoryID")]
        public System.String ID { get; set; }

        public System.String TerritoryDescription { get; set; }

        public RegionUpdateTest Region { get; set; }
    }

}