//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace FelineSoft.CatFlap.NorthwindTests
{
    public class Employee_EmployeeQueryTest
    {
        public System.Int32 EmployeeID { get; set; }

        public System.Collections.Generic.ICollection<Order_EmployeeQueryTest> Orders { get; set; }

    }

    public class Order_Detail_EmployeeQueryTest
    {
        public System.Int32 OrderID { get; set; }

        public System.Int32 ProductID { get; set; }

    }

    public class Order_EmployeeQueryTest
    {
        public System.Int32 OrderID { get; set; }

        public System.Collections.Generic.ICollection<Order_Detail_EmployeeQueryTest> Order_Details { get; set; }

        public bool Deleted { get; set; }

        public Nullable<int> ShipVia { get; set; }
    }

}