//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace $rootnamespace$
{
    public class $safeitemname$ : CatFlap<$contexttype$>
    {
        public $safeitemname$()
            : base(() => new $contexttype$())
        {
            $accessorinstantiation$        }

        $accessordefinition$
    }
}