//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace App
{
    public class CustomerVM
    {
        [MapTo(typeof(DomainModel.Customer), "CustomerID")]
        public System.String ID { get; set; }

        public System.String CompanyName { get; set; }

        public System.String ContactName { get; set; }

        public System.String Phone { get; set; }

        public System.Collections.Generic.ICollection<OrderVM> Orders { get; set; }

    }

    public class OrderDetailVM
    {
        public System.Decimal UnitPrice { get; set; }

        public System.Int16 Quantity { get; set; }

        public System.Single Discount { get; set; }

        public ProductVM Product { get; set; }

    }

    public class OrderVM
    {
        [MapTo(typeof(DomainModel.Order), "OrderID")]
        public System.Int32 ID { get; set; }

        public System.Nullable<System.DateTime> OrderDate { get; set; }

        public System.Collections.Generic.ICollection<OrderDetailVM> Order_Details { get; set; }

    }

    public class ProductVM
    {
        [MapTo(typeof(DomainModel.Product), "ProductID")]
        public System.Int32 ID { get; set; }

        public System.String ProductName { get; set; }

    }

}