//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace App
{
    public class NewCustomersVM
    {
        public System.String CompanyName { get; set; }

        public System.String ContactName { get; set; }

    }

    public class NewOrdersVM
    {
        public System.Int32 OrderID { get; set; }

        public System.String ShipCity { get; set; }

        public NewCustomersVM Customer { get; set; }

        public DateTime? OrderDate { get; set; }

        public override string ToString()
        {
            return OrderDate.ToString();
        }
    }

}