//
//  This file was generated by the CatFlap extension
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace DomainModel
{
    public class EntitiesCatFlap : CatFlap<DomainModel.Entities>
    {
        public EntitiesCatFlap()
            : base(() => new DomainModel.Entities())
        {
            tblAccounts = CreateAccessor<global::DomainModel.tblAccount>();
            tblAccountBackups = CreateAccessor<global::DomainModel.tblAccountBackup>();
            tblAccountBalances = CreateAccessor<global::DomainModel.tblAccountBalance>();
            tblAccountBalanceAudits = CreateAccessor<global::DomainModel.tblAccountBalanceAudit>();
            tblAccountChanges = CreateAccessor<global::DomainModel.tblAccountChange>();
            tblAccountDisclaimers = CreateAccessor<global::DomainModel.tblAccountDisclaimer>();
            tblAccountImages = CreateAccessor<global::DomainModel.tblAccountImage>();
            tblAccountNews = CreateAccessor<global::DomainModel.tblAccountNew>();
            tblAccountPreferences = CreateAccessor<global::DomainModel.tblAccountPreference>();
            tblAssets = CreateAccessor<global::DomainModel.tblAsset>();
            tblBalanceTypes = CreateAccessor<global::DomainModel.tblBalanceType>();
            tblBeds = CreateAccessor<global::DomainModel.tblBed>();
            tblBedTypes = CreateAccessor<global::DomainModel.tblBedType>();
            tblCabins = CreateAccessor<global::DomainModel.tblCabin>();
            tblCallRequests = CreateAccessor<global::DomainModel.tblCallRequest>();
            tblCashOuts = CreateAccessor<global::DomainModel.tblCashOut>();
            tblCashOutValues = CreateAccessor<global::DomainModel.tblCashOutValue>();
            tblCodes = CreateAccessor<global::DomainModel.tblCode>();
            tblComponents = CreateAccessor<global::DomainModel.tblComponent>();
            tblDisclaimers = CreateAccessor<global::DomainModel.tblDisclaimer>();
            tblFingerPrints = CreateAccessor<global::DomainModel.tblFingerPrint>();
            tblFloats = CreateAccessor<global::DomainModel.tblFloat>();
            tblFloatValues = CreateAccessor<global::DomainModel.tblFloatValue>();
            tblGiftCards = CreateAccessor<global::DomainModel.tblGiftCard>();
            tblImages = CreateAccessor<global::DomainModel.tblImage>();
            tblImageTypes = CreateAccessor<global::DomainModel.tblImageType>();
            tblImageUploads = CreateAccessor<global::DomainModel.tblImageUpload>();
            tblInfoes = CreateAccessor<global::DomainModel.tblInfo>();
            tblKioskInfoes = CreateAccessor<global::DomainModel.tblKioskInfo>();
            tblLogIns = CreateAccessor<global::DomainModel.tblLogIn>();
            tblOffers = CreateAccessor<global::DomainModel.tblOffer>();
            tblPreferences = CreateAccessor<global::DomainModel.tblPreference>();
            tblPreparedTexts = CreateAccessor<global::DomainModel.tblPreparedText>();
            tblReports = CreateAccessor<global::DomainModel.tblReport>();
            tblScripts = CreateAccessor<global::DomainModel.tblScript>();
            tblSecurityGroups = CreateAccessor<global::DomainModel.tblSecurityGroup>();
            tblSecurityPermissions = CreateAccessor<global::DomainModel.tblSecurityPermission>();
            tblSettings = CreateAccessor<global::DomainModel.tblSetting>();
            tblSettingsSymbols = CreateAccessor<global::DomainModel.tblSettingsSymbol>();
            tblSideBarMessages = CreateAccessor<global::DomainModel.tblSideBarMessage>();
            tblSignupInfoes = CreateAccessor<global::DomainModel.tblSignupInfo>();
            tblSites = CreateAccessor<global::DomainModel.tblSite>();
            tblSiteAds = CreateAccessor<global::DomainModel.tblSiteAd>();
            tblSiteGroups = CreateAccessor<global::DomainModel.tblSiteGroup>();
            tblSiteSettings = CreateAccessor<global::DomainModel.tblSiteSetting>();
            tblSkypeAccounts = CreateAccessor<global::DomainModel.tblSkypeAccount>();
            tblSoftwareUpdaters = CreateAccessor<global::DomainModel.tblSoftwareUpdater>();
            tblStaffLogins = CreateAccessor<global::DomainModel.tblStaffLogin>();
            tblTransactions = CreateAccessor<global::DomainModel.tblTransaction>();
            tblTransactionCabins = CreateAccessor<global::DomainModel.tblTransactionCabin>();
            tblTransactionCashes = CreateAccessor<global::DomainModel.tblTransactionCash>();
            tblTransactionGiftCards = CreateAccessor<global::DomainModel.tblTransactionGiftCard>();
            tblTransactionPayments = CreateAccessor<global::DomainModel.tblTransactionPayment>();
            tblTransactionTopups = CreateAccessor<global::DomainModel.tblTransactionTopup>();
            tblTransactionVendings = CreateAccessor<global::DomainModel.tblTransactionVending>();
            tblTransactionVouchers = CreateAccessor<global::DomainModel.tblTransactionVoucher>();
            tblUpdateLogs = CreateAccessor<global::DomainModel.tblUpdateLog>();
            tblVendings = CreateAccessor<global::DomainModel.tblVending>();
            tblVendItems = CreateAccessor<global::DomainModel.tblVendItem>();
            tblVersions = CreateAccessor<global::DomainModel.tblVersion>();
            tblVouchers = CreateAccessor<global::DomainModel.tblVoucher>();
        }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccount> tblAccounts { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountBackup> tblAccountBackups { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountBalance> tblAccountBalances { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountBalanceAudit> tblAccountBalanceAudits { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountChange> tblAccountChanges { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountDisclaimer> tblAccountDisclaimers { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountImage> tblAccountImages { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountNew> tblAccountNews { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAccountPreference> tblAccountPreferences { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblAsset> tblAssets { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblBalanceType> tblBalanceTypes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblBed> tblBeds { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblBedType> tblBedTypes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblCabin> tblCabins { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblCallRequest> tblCallRequests { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblCashOut> tblCashOuts { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblCashOutValue> tblCashOutValues { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblCode> tblCodes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblComponent> tblComponents { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblDisclaimer> tblDisclaimers { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblFingerPrint> tblFingerPrints { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblFloat> tblFloats { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblFloatValue> tblFloatValues { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblGiftCard> tblGiftCards { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblImage> tblImages { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblImageType> tblImageTypes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblImageUpload> tblImageUploads { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblInfo> tblInfoes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblKioskInfo> tblKioskInfoes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblLogIn> tblLogIns { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblOffer> tblOffers { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblPreference> tblPreferences { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblPreparedText> tblPreparedTexts { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblReport> tblReports { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblScript> tblScripts { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSecurityGroup> tblSecurityGroups { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSecurityPermission> tblSecurityPermissions { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSetting> tblSettings { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSettingsSymbol> tblSettingsSymbols { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSideBarMessage> tblSideBarMessages { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSignupInfo> tblSignupInfoes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSite> tblSites { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSiteAd> tblSiteAds { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSiteGroup> tblSiteGroups { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSiteSetting> tblSiteSettings { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSkypeAccount> tblSkypeAccounts { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblSoftwareUpdater> tblSoftwareUpdaters { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblStaffLogin> tblStaffLogins { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransaction> tblTransactions { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionCabin> tblTransactionCabins { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionCash> tblTransactionCashes { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionGiftCard> tblTransactionGiftCards { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionPayment> tblTransactionPayments { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionTopup> tblTransactionTopups { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionVending> tblTransactionVendings { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblTransactionVoucher> tblTransactionVouchers { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblUpdateLog> tblUpdateLogs { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblVending> tblVendings { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblVendItem> tblVendItems { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblVersion> tblVersions { get; private set; }

        public ISetAccessor<global::DomainModel.Entities, global::DomainModel.tblVoucher> tblVouchers { get; private set; }


    }
}