//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountBalanceAudit
    {
        public long ID { get; set; }
        public Nullable<long> BalanceID { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<long> TransactionAccountID { get; set; }
        public Nullable<long> TransactionSiteID { get; set; }
        public Nullable<System.DateTime> TransactionTimestamp { get; set; }
    
        public virtual tblAccountBalance tblAccountBalance { get; set; }
    }
}
