//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public tblAccount()
        {
            this.tblStaffLogins = new HashSet<tblStaffLogin>();
            this.tblAccountBalances = new HashSet<tblAccountBalance>();
            this.tblAccountChanges = new HashSet<tblAccountChange>();
            this.tblAccountChanges1 = new HashSet<tblAccountChange>();
            this.tblAccountImages = new HashSet<tblAccountImage>();
            this.tblAccountPreferences = new HashSet<tblAccountPreference>();
            this.tblCashOuts = new HashSet<tblCashOut>();
            this.tblAccountDisclaimers = new HashSet<tblAccountDisclaimer>();
            this.tblFingerPrints = new HashSet<tblFingerPrint>();
            this.tblLogIns = new HashSet<tblLogIn>();
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string PostCode { get; set; }
        public string PinNumber { get; set; }
        public Nullable<long> SiteID { get; set; }
        public Nullable<bool> Female { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public string SuspendMessage { get; set; }
        public bool IsStaffMember { get; set; }
        public Nullable<long> SecurityGroupId { get; set; }
        public int FailedLoginAttempts { get; set; }
        public string Message { get; set; }
        public Nullable<bool> HasReadMessage { get; set; }
        public string PrivateNote { get; set; }
    
        public virtual ICollection<tblStaffLogin> tblStaffLogins { get; set; }
        public virtual tblSecurityGroup tblSecurityGroup { get; set; }
        public virtual ICollection<tblAccountBalance> tblAccountBalances { get; set; }
        public virtual ICollection<tblAccountChange> tblAccountChanges { get; set; }
        public virtual ICollection<tblAccountChange> tblAccountChanges1 { get; set; }
        public virtual ICollection<tblAccountImage> tblAccountImages { get; set; }
        public virtual ICollection<tblAccountPreference> tblAccountPreferences { get; set; }
        public virtual ICollection<tblCashOut> tblCashOuts { get; set; }
        public virtual ICollection<tblAccountDisclaimer> tblAccountDisclaimers { get; set; }
        public virtual ICollection<tblFingerPrint> tblFingerPrints { get; set; }
        public virtual ICollection<tblLogIn> tblLogIns { get; set; }
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
