//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountImage
    {
        public long AccountID { get; set; }
        public long ImageID { get; set; }
        public Nullable<bool> IsProfileImage { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblImage tblImage { get; set; }
    }
}
