//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public tblAsset()
        {
            this.tblCabins = new HashSet<tblCabin>();
        }
    
        public long ID { get; set; }
        public string AssetNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> TubeHours { get; set; }
        public Nullable<int> BedHours { get; set; }
        public Nullable<long> BedID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblBed tblBed { get; set; }
        public virtual ICollection<tblCabin> tblCabins { get; set; }
    }
}
