//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBedType
    {
        public tblBedType()
        {
            this.tblBeds = new HashSet<tblBed>();
            this.tblDisclaimers = new HashSet<tblDisclaimer>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string SubTitle { get; set; }
        public Nullable<long> BalanceTypeID { get; set; }
        public Nullable<bool> HasTubes { get; set; }
        public string Code { get; set; }
    
        public virtual tblBalanceType tblBalanceType { get; set; }
        public virtual ICollection<tblBed> tblBeds { get; set; }
        public virtual ICollection<tblDisclaimer> tblDisclaimers { get; set; }
    }
}
