//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBalanceType
    {
        public tblBalanceType()
        {
            this.tblAccountBalances = new HashSet<tblAccountBalance>();
            this.tblBedTypes = new HashSet<tblBedType>();
            this.tblOffers = new HashSet<tblOffer>();
            this.tblTransactionPayments = new HashSet<tblTransactionPayment>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Units { get; set; }
        public string ShortUnits { get; set; }
        public string Colour { get; set; }
        public Nullable<long> PanelImageID { get; set; }
        public Nullable<long> SmallPanelImageID { get; set; }
        public Nullable<bool> IsNumericType { get; set; }
        public Nullable<bool> IsDateType { get; set; }
        public Nullable<bool> IsCustomerBalance { get; set; }
    
        public virtual ICollection<tblAccountBalance> tblAccountBalances { get; set; }
        public virtual tblImage tblImage { get; set; }
        public virtual tblImage tblImage1 { get; set; }
        public virtual ICollection<tblBedType> tblBedTypes { get; set; }
        public virtual ICollection<tblOffer> tblOffers { get; set; }
        public virtual ICollection<tblTransactionPayment> tblTransactionPayments { get; set; }
    }
}
