//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallRequest
    {
        public long ID { get; set; }
        public Nullable<long> SiteID { get; set; }
        public string RequestType { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Female { get; set; }
        public string Phone { get; set; }
        public string Pin { get; set; }
        public string Email { get; set; }
        public string Postcode { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
