//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisclaimer
    {
        public tblDisclaimer()
        {
            this.tblAccountDisclaimers = new HashSet<tblAccountDisclaimer>();
        }
    
        public long ID { get; set; }
        public Nullable<long> BedTypeID { get; set; }
        public string Disclaimer { get; set; }
    
        public virtual ICollection<tblAccountDisclaimer> tblAccountDisclaimers { get; set; }
        public virtual tblBedType tblBedType { get; set; }
    }
}
