//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFloat
    {
        public tblFloat()
        {
            this.tblFloatValues = new HashSet<tblFloatValue>();
        }
    
        public long ID { get; set; }
        public Nullable<long> SiteID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<long> AccountID { get; set; }
        public Nullable<decimal> OldFloat { get; set; }
        public Nullable<decimal> NewFloat { get; set; }
    
        public virtual ICollection<tblFloatValue> tblFloatValues { get; set; }
    }
}
