//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public tblImage()
        {
            this.tblAccountImages = new HashSet<tblAccountImage>();
            this.tblBalanceTypes = new HashSet<tblBalanceType>();
            this.tblBalanceTypes1 = new HashSet<tblBalanceType>();
            this.tblBeds = new HashSet<tblBed>();
            this.tblGiftCards = new HashSet<tblGiftCard>();
            this.tblOffers = new HashSet<tblOffer>();
            this.tblOffers1 = new HashSet<tblOffer>();
            this.tblSiteAds = new HashSet<tblSiteAd>();
            this.tblVendItems = new HashSet<tblVendItem>();
        }
    
        public long ID { get; set; }
        public string OriginalFileName { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<bool> System { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> ImageTypeId { get; set; }
    
        public virtual ICollection<tblAccountImage> tblAccountImages { get; set; }
        public virtual ICollection<tblBalanceType> tblBalanceTypes { get; set; }
        public virtual ICollection<tblBalanceType> tblBalanceTypes1 { get; set; }
        public virtual ICollection<tblBed> tblBeds { get; set; }
        public virtual ICollection<tblGiftCard> tblGiftCards { get; set; }
        public virtual tblImageType tblImageType { get; set; }
        public virtual ICollection<tblOffer> tblOffers { get; set; }
        public virtual ICollection<tblOffer> tblOffers1 { get; set; }
        public virtual ICollection<tblSiteAd> tblSiteAds { get; set; }
        public virtual ICollection<tblVendItem> tblVendItems { get; set; }
    }
}
