//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImageType
    {
        public tblImageType()
        {
            this.tblImages = new HashSet<tblImage>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblImage> tblImages { get; set; }
    }
}
