//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOffer
    {
        public tblOffer()
        {
            this.tblTransactionTopups = new HashSet<tblTransactionTopup>();
        }
    
        public long ID { get; set; }
        public Nullable<long> BalanceTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<long> CardImageID { get; set; }
        public Nullable<long> AdImageID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblBalanceType tblBalanceType { get; set; }
        public virtual tblImage tblImage { get; set; }
        public virtual tblImage tblImage1 { get; set; }
        public virtual ICollection<tblTransactionTopup> tblTransactionTopups { get; set; }
    }
}
