//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreparedText
    {
        public int ID { get; set; }
        public int CallType { get; set; }
        public int DisplayOrder { get; set; }
        public string Text { get; set; }
    }
}
