//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public tblReport()
        {
            this.tblSecurityGroups = new HashSet<tblSecurityGroup>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public bool DisplayDateFilter { get; set; }
        public bool DisplaySiteFilter { get; set; }
        public bool DisplayVoucherFilter { get; set; }
    
        public virtual ICollection<tblSecurityGroup> tblSecurityGroups { get; set; }
    }
}
