//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityGroup
    {
        public tblSecurityGroup()
        {
            this.tblAccounts = new HashSet<tblAccount>();
            this.tblReports = new HashSet<tblReport>();
            this.tblSecurityPermissions = new HashSet<tblSecurityPermission>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
        public virtual ICollection<tblReport> tblReports { get; set; }
        public virtual ICollection<tblSecurityPermission> tblSecurityPermissions { get; set; }
    }
}
