//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScript
    {
        public tblScript()
        {
            this.tblSoftwareUpdaters = new HashSet<tblSoftwareUpdater>();
            this.tblSoftwareUpdaters1 = new HashSet<tblSoftwareUpdater>();
            this.tblSoftwareUpdaters2 = new HashSet<tblSoftwareUpdater>();
            this.tblUpdateLogs = new HashSet<tblUpdateLog>();
            this.tblUpdateLogs1 = new HashSet<tblUpdateLog>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Script { get; set; }
    
        public virtual ICollection<tblSoftwareUpdater> tblSoftwareUpdaters { get; set; }
        public virtual ICollection<tblSoftwareUpdater> tblSoftwareUpdaters1 { get; set; }
        public virtual ICollection<tblSoftwareUpdater> tblSoftwareUpdaters2 { get; set; }
        public virtual ICollection<tblUpdateLog> tblUpdateLogs { get; set; }
        public virtual ICollection<tblUpdateLog> tblUpdateLogs1 { get; set; }
    }
}
