//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        public tblSite()
        {
            this.tblCabins = new HashSet<tblCabin>();
            this.tblCashOuts = new HashSet<tblCashOut>();
            this.tblCodes = new HashSet<tblCode>();
            this.tblLogIns = new HashSet<tblLogIn>();
            this.tblSiteSettings = new HashSet<tblSiteSetting>();
            this.tblSoftwareUpdaters = new HashSet<tblSoftwareUpdater>();
            this.tblStaffLogins = new HashSet<tblStaffLogin>();
            this.tblUpdateLogs = new HashSet<tblUpdateLog>();
            this.tblSiteAds = new HashSet<tblSiteAd>();
            this.tblTransactions = new HashSet<tblTransaction>();
            this.tblVendings = new HashSet<tblVending>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string OpenTimes { get; set; }
        public string CloseTimes { get; set; }
        public Nullable<int> LightsOn { get; set; }
        public Nullable<int> LightsOff { get; set; }
        public Nullable<int> BedWarmup { get; set; }
        public Nullable<int> SignOn { get; set; }
        public Nullable<int> SignOff { get; set; }
        public string IPAddress { get; set; }
        public string WarmupCabins { get; set; }
        public Nullable<bool> NoGuestAuth { get; set; }
        public Nullable<bool> NoChange { get; set; }
        public Nullable<int> FingerprintMatch { get; set; }
        public Nullable<System.TimeSpan> HappyHourMonSatStart { get; set; }
        public Nullable<System.TimeSpan> HappyHourMonSatEnd { get; set; }
        public Nullable<decimal> HappyHourMonSatDiscount { get; set; }
        public Nullable<System.TimeSpan> HappyHourSunStart { get; set; }
        public Nullable<System.TimeSpan> HappyHourSunEnd { get; set; }
        public Nullable<decimal> HappyHourSunDiscount { get; set; }
        public Nullable<bool> CheckFloat { get; set; }
        public string HappyHourMessage { get; set; }
        public Nullable<long> SiteGroupId { get; set; }
    
        public virtual ICollection<tblCabin> tblCabins { get; set; }
        public virtual ICollection<tblCashOut> tblCashOuts { get; set; }
        public virtual ICollection<tblCode> tblCodes { get; set; }
        public virtual ICollection<tblLogIn> tblLogIns { get; set; }
        public virtual ICollection<tblSiteSetting> tblSiteSettings { get; set; }
        public virtual ICollection<tblSoftwareUpdater> tblSoftwareUpdaters { get; set; }
        public virtual ICollection<tblStaffLogin> tblStaffLogins { get; set; }
        public virtual ICollection<tblUpdateLog> tblUpdateLogs { get; set; }
        public virtual tblSiteGroup tblSiteGroup { get; set; }
        public virtual ICollection<tblSiteAd> tblSiteAds { get; set; }
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
        public virtual ICollection<tblVending> tblVendings { get; set; }
    }
}
