//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteGroup
    {
        public tblSiteGroup()
        {
            this.tblSites = new HashSet<tblSite>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblSite> tblSites { get; set; }
    }
}
