//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoftwareUpdater
    {
        public tblSoftwareUpdater()
        {
            this.tblUpdateLogs = new HashSet<tblUpdateLog>();
        }
    
        public long SiteID { get; set; }
        public string Component { get; set; }
        public string TargetVersion { get; set; }
        public string LastReportedVersion { get; set; }
        public Nullable<System.Guid> PreExecuteScript { get; set; }
        public Nullable<System.Guid> PostExecuteScript { get; set; }
        public Nullable<System.Guid> AdHocScript { get; set; }
        public Nullable<System.DateTime> AdHocScriptExecuteTime { get; set; }
        public bool AdHocScriptExecuted { get; set; }
        public string AdHocScriptOutput { get; set; }
        public System.TimeSpan UpdateSchedule { get; set; }
        public bool GetLatestSettings { get; set; }
        public bool RunAdHocImmediately { get; set; }
    
        public virtual tblScript tblScript { get; set; }
        public virtual tblScript tblScript1 { get; set; }
        public virtual tblScript tblScript2 { get; set; }
        public virtual tblSite tblSite { get; set; }
        public virtual tblSoftwareUpdater tblSoftwareUpdater1 { get; set; }
        public virtual tblSoftwareUpdater tblSoftwareUpdater2 { get; set; }
        public virtual ICollection<tblUpdateLog> tblUpdateLogs { get; set; }
    }
}
