//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionPayment
    {
        public long ID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<long> BalanceTypeID { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        public virtual tblBalanceType tblBalanceType { get; set; }
        public virtual tblTransaction tblTransaction { get; set; }
    }
}
