//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public tblTransaction()
        {
            this.tblTransactionCabins = new HashSet<tblTransactionCabin>();
            this.tblTransactionCashes = new HashSet<tblTransactionCash>();
            this.tblTransactionGiftCards = new HashSet<tblTransactionGiftCard>();
            this.tblTransactionPayments = new HashSet<tblTransactionPayment>();
            this.tblTransactionTopups = new HashSet<tblTransactionTopup>();
            this.tblTransactionVendings = new HashSet<tblTransactionVending>();
            this.tblTransactionVouchers = new HashSet<tblTransactionVoucher>();
        }
    
        public long ID { get; set; }
        public Nullable<long> AccountID { get; set; }
        public Nullable<long> SiteID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<bool> FromDesktop { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblSite tblSite { get; set; }
        public virtual ICollection<tblTransactionCabin> tblTransactionCabins { get; set; }
        public virtual ICollection<tblTransactionCash> tblTransactionCashes { get; set; }
        public virtual ICollection<tblTransactionGiftCard> tblTransactionGiftCards { get; set; }
        public virtual ICollection<tblTransactionPayment> tblTransactionPayments { get; set; }
        public virtual ICollection<tblTransactionTopup> tblTransactionTopups { get; set; }
        public virtual ICollection<tblTransactionVending> tblTransactionVendings { get; set; }
        public virtual ICollection<tblTransactionVoucher> tblTransactionVouchers { get; set; }
    }
}
