//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpdateLog
    {
        public System.Guid ID { get; set; }
        public Nullable<long> SiteID { get; set; }
        public string TargetVersion { get; set; }
        public string PreviousVersion { get; set; }
        public Nullable<bool> UpdateSuccess { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.Guid> PreExecuteScript { get; set; }
        public Nullable<System.Guid> PostExecuteScript { get; set; }
        public string PreExecuteScriptOutput { get; set; }
        public string PostExecuteScriptOutput { get; set; }
        public string Component { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual tblScript tblScript { get; set; }
        public virtual tblScript tblScript1 { get; set; }
        public virtual tblSite tblSite { get; set; }
        public virtual tblSoftwareUpdater tblSoftwareUpdater { get; set; }
    }
}
