//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendItem
    {
        public tblVendItem()
        {
            this.tblTransactionVendings = new HashSet<tblTransactionVending>();
            this.tblVendings = new HashSet<tblVending>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> ImageID { get; set; }
        public string Offer { get; set; }
        public string OfferColour { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblImage tblImage { get; set; }
        public virtual ICollection<tblTransactionVending> tblTransactionVendings { get; set; }
        public virtual ICollection<tblVending> tblVendings { get; set; }
    }
}
