//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher
    {
        public tblVoucher()
        {
            this.tblTransactionGiftCards = new HashSet<tblTransactionGiftCard>();
            this.tblTransactionVouchers = new HashSet<tblTransactionVoucher>();
        }
    
        public long ID { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual ICollection<tblTransactionGiftCard> tblTransactionGiftCards { get; set; }
        public virtual ICollection<tblTransactionVoucher> tblTransactionVouchers { get; set; }
    }
}
