//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVending
    {
        public long ID { get; set; }
        public Nullable<long> SiteID { get; set; }
        public Nullable<long> VendItemID { get; set; }
        public Nullable<byte> ShelfNumber { get; set; }
        public Nullable<byte> Quantity { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<byte> MaxItems { get; set; }
    
        public virtual tblSite tblSite { get; set; }
        public virtual tblVendItem tblVendItem { get; set; }
    }
}
