//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace DataService
{
    public class CatFlap3 : CatFlap<$contexttype$>
    {
        public CatFlap3()
            : base(() => new $contexttype$())
        {
                    }

        
    }
}