//This file was generated by the CatFlap item template

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FelineSoft.CatFlap;

namespace DataService
{
    public class nwNoFKsFlap : CatFlap<DomainModel.NORTH2Entities>
    {
        public nwNoFKsFlap()
            : base(() => new DomainModel.NORTH2Entities())
        {
            Categories = CreateAccessor<global::DomainModel.Category>();
            CustomerDemographics = CreateAccessor<global::DomainModel.CustomerDemographic>();
            Customers = CreateAccessor<global::DomainModel.Customer>();
            Employees = CreateAccessor<global::DomainModel.Employee>();
            Order_Details = CreateAccessor<global::DomainModel.Order_Detail>();
            Orders = CreateAccessor<global::DomainModel.Order>();
            Products = CreateAccessor<global::DomainModel.Product>();
            Regions = CreateAccessor<global::DomainModel.Region>();
            Shippers = CreateAccessor<global::DomainModel.Shipper>();
            Suppliers = CreateAccessor<global::DomainModel.Supplier>();
            Territories = CreateAccessor<global::DomainModel.Territory>();
        }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Category> Categories { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.CustomerDemographic> CustomerDemographics { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Customer> Customers { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Employee> Employees { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Order_Detail> Order_Details { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Order> Orders { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Product> Products { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Region> Regions { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Shipper> Shippers { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Supplier> Suppliers { get; private set; }

        public ISetAccessor<global::DomainModel.NORTH2Entities, global::DomainModel.Territory> Territories { get; private set; }


    }
}